version: "3.8"

services:
  server:
    # image: "nginx:stable-alpine"
    build: 
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes: 
      # Mount because of source code live reload on container
      - ./src:/var/www/html  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      # Mount for installation of the project base template (run this service 1st)
      - ./src:/var/www/html
  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - ./src:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html

    