version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: kevin
      #MONGO_INITDB_ROOT_PASSWORD: secret
    env_file: 
      - ./env/mongo.env

  # backend:
  #   image: 

  # frontend:
  #   image: 
